name: supabase_edge_aggregator
description: A Supaabase Edge Function to aggregate match scouting data.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  edge: ^0.0.5
  edge_http_client: ^0.0.1+3
  supabase: ^1.9.5
  supabase_functions: ^0.0.1

dev_dependencies:
  lints: ^2.0.1