name: birdseye
description: FRC Scouting App
publish_to: 'none'
version: 2.1.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.17+3
  flutter_svg: ^2.0.7
  flutter_swipe_action_cell: ^3.1.2
  go_router: ^13.1.0
  http: ^1.0.0
  localstore: ^1.3.5
  shared_preferences: ^2.1.2
  stock: ^1.0.1
  supabase_flutter: ^2.3.1
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/documents/
  fonts:
    - family: HemiHead
      fonts:
        - asset: assets/fonts/hemi-head.otf
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Verdana
      fonts:
        - asset: assets/fonts/verdana.ttf
        - asset: assets/fonts/verdanai.ttf
          style: italic
        - asset: assets/fonts/verdanab.ttf
          weight: 700
        - asset: assets/fonts/verdanaz.ttf
          style: italic
          weight: 700