name: Autobuild
run-name: ${{ github.actor }} building flutter
on:
  push:
    branches: ["main"]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:version:-:hash:'
          cache-path: ${{ runner.tool_cache }}/flutter/
      - name: Install Dependencies
        run: flutter pub get
  build-apk:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true
        cache-key: 'flutter-:os:-:version:-:hash:'
        cache-path: ${{ runner.tool_cache }}/flutter/
    - name: Build APK
      run: flutter build apk --split-per-abi
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk-dist
        path: build/app/outputs/flutter-apk/*.apk
  publish:
    needs: build-apk
    name: "Publish"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "marvinpinto/action-automatic-releases@latest"
       with:
         repo_token: "${{ secrets.GITHUB_TOKEN }}"
         automatic_release_tag: "latest"
         prerelease: true
         title: "Android Development Build"
         files: build/app/outputs/flutter-apk/*.apk